name: wafdemo
version: 0.1
summary: out of tree waf demo for snapcraft
description: host waf integration test bits out of snapcraft tree
confinement: strict

# this provides the c based demo of waf
parts:
  wafdemo:
    plugin: waf
    source: .
    configflags:
      - --progress
      - --verbose
